### ISSUE TITLE
add read_timeout and open_timeout to client.rb

### ISSUE THREAD

**Issue by privateip** [arista-eosplus/rbeapi#10]
this issue is to track adding optional keyword args for #config and #enable to set the timeout values.  Values should be transparently passed through #run_commands to eapilib.  If the values are not specified in the method (set to nil) then the default values are to be invoked in eapilib.

timeout values should also be configurable via eapi.conf 

references:
* See #9 
* https://github.com/arista-eosplus/rbeapi/blob/cb26b20d8723ed0dd439b33917b6df166dd21c6f/lib/rbeapi/client.rb#L334
* https://github.com/arista-eosplus/rbeapi/blob/cb26b20d8723ed0dd439b33917b6df166dd21c6f/lib/rbeapi/client.rb#L312
* https://github.com/arista-eosplus/rbeapi/blob/cb26b20d8723ed0dd439b33917b6df166dd21c6f/lib/rbeapi/client.rb#L389

**Comment by devrobo** [comment]
Fixed with commit a94817e3954c96d66040d545a7c4500e3cf862d5
