### ISSUE TITLE
can't rake all_rpms

### ISSUE THREAD

**Issue by lunarman** [arista-eosplus/rbeapi#11]
hi, my intention is to build all necessary rpms to later build swix in my eos switch. 
but i kept running into rake problem. like for example, if i generate individual inifile below.. 
my host is ubuntu 12.04.05. i tried to install gawk, mawk, original awk.. all of them failed..
my ruby/gem/rake experience is nil to nothing. 
can you help? thanks!

me@chloroplast:~/src/rbeapi$ sudo rake inifile
Usage: awk [POSIX or GNU style options] -f progfile [--] file ...
Usage: awk [POSIX or GNU style options] [--] 'program' file ...
POSIX options:		GNU long options:
	-f progfile		--file=progfile
	-F fs			--field-separator=fs
	-v var=val		--assign=var=val
	-m[fr] val
	-O			--optimize
	-W compat		--compat
	-W copyleft		--copyleft
	-W copyright		--copyright
	-W dump-variables[=file]	--dump-variables[=file]
	-W exec=file		--exec=file
	-W gen-po		--gen-po
	-W help			--help
	-W lint[=fatal]		--lint[=fatal]
	-W lint-old		--lint-old
	-W non-decimal-data	--non-decimal-data
	-W profile[=file]	--profile[=file]
	-W posix		--posix
	-W re-interval		--re-interval
	-W source=program-text	--source=program-text
	-W traditional		--traditional
	-W usage		--usage
	-W use-lc-numeric	--use-lc-numeric
	-W version		--version

To report bugs, see node `Bugs' in `gawk.info', which is
section `Reporting Problems and Bugs' in the printed version.

gawk is a pattern scanning and processing language.
By default it reads standard input and writes standard output.

Examples:
	gawk '{ sum += $1 }; END { print sum }' file
	gawk -F: '{ print $1 }' /etc/passwd
ERROR:  While executing gem ... (ArgumentError)
    Illformed requirement ["="]
Building rpm for inifile ()
error: line 5: Empty tag: Version:
error: line 5: Empty tag: Version:
RPMs are available in rpms/noarch/    ---- it's a lie!!

**Comment by jerearista** [comment]
We generally build RedHat-based packages on RedHat-based systems.   It looks like you hit an issue with such an old version of awk that doesn't support '-e' (--source='program-text') and you would likely also hit an issue in which rpmbuild on Ubuntu does not auto-create the buildroot directory as the official rpmbuild does.    Please try out the ubuntu-rpmbuild branch.    I've tested these changes on Ubuntu 14.04.2.

Additionally, there is no need to prefix rpmbuild with sudo.

    rbeapi$ git fetch
    rbeapi$ git checkout ubuntu-rpmbuild
    rbeapi$ rake all_rpms

**Comment by lunarman** [comment]
Great, it works now. 
But i ran into another issue in the switch.
i'll open another discussion since it might not be related to this one. 
thanks a lot for the quick turnaround.
