### ISSUE TITLE
the "running_config" api error

### ISSUE THREAD

**Issue by PeiwenChen** [arista-eosplus/rbeapi#127]
hi,

The `running_config` calls `get_config`, and it uses `strip` in these two lines.
https://github.com/arista-eosplus/rbeapi/blob/7ad79fad49304e26c4b8a0fcb69e93938bff519b/lib/rbeapi/client.rb#L515-L516

What about the config result is nil? and then the `strip` will fail?

**Comment by devrobo** [comment]
Hi,
Thank you for pointing out this issue. Is this currently impacting you or can it wait to be fixed in the next release next month?

John

**Comment by PeiwenChen** [comment]
Hi John,

It does not block me currently.
Yeah, I am fine to wait for the next release.
Thanks taking care of it!

Peiwen
