### ISSUE TITLE
'create swix' fails, can i --force?

### ISSUE THREAD

**Issue by lunarman** [arista-eosplus/rbeapi#13]
i've got a couple of questions/probs - might be easy ones for you to solve:
1. which rbeapi should i upload to the switch? is the pe-* or the rubygem-* ?
2. the 'swix create' fails to bundle the rpms, what's up with that? is it safe to use --force option?
3. how can i tell if rbeapi is installed properly? (i've enabled eapi with both http and unix-socket)
4. my next step is to install puppet-eos... stay tune.

thanks for all the support!!

[admin@sw1 flash]$ swix create rbeapi-0.1.0-eos4.swix *rubygem*.rpm
  adding: manifest.txt (stored 0%)
  adding: pe-rubygem-inifile-3.0.0-2.eos4.noarch.rpm (stored 0%)
  adding: pe-rubygem-rbeapi-0.1.0-1.eos4.noarch.rpm (stored 0%)
  adding: pe-rubygem-rbeapi-0.1.0-2.eos4.noarch.rpm (stored 0%)
  adding: rubygem-inifile-3.0.0-2.eos4.noarch.rpm (stored 0%)
  adding: rubygem-net_http_unix-0.2.1-2.eos4.noarch.rpm (stored 0%)
  adding: rubygem-rbeapi-0.1.0-1.eos4.noarch.rpm (stored 0%)
  adding: rubygem-rbeapi-0.1.0-2.eos4.noarch.rpm (stored 0%)
[admin@sw1 flash]$ logout
sw1#config
sw1(config)#copy flash:rbeapi-0.1.0-eos4.swix extension:
Copy completed successfully.
sw1(config)#extension rbeapi-0.1.0-eos4.swix
% Error installing rbeapi-0.1.0-eos4.swix: RPM install error: Transaction check failed: pe-ruby is needed by pe-rubygem-inifile-3.0.0-2.eos4.noarch
pe-rubygems is needed by pe-rubygem-inifile-3.0.0-2.eos4.noarch
pe-ruby is needed by pe-rubygem-rbeapi-0.1.0-2.eos4.noarch
pe-rubygem(net-http-unix) is needed by pe-rubygem-rbeapi-0.1.0-2.eos4.noarch
pe-rubygems is needed by pe-rubygem-rbeapi-0.1.0-2.eos4.noarch
ruby(abi) = %{rubyabi} is needed by rubygem-inifile-3.0.0-2.eos4.noarch
ruby(abi) = %{rubyabi} is needed by rubygem-net_http_unix-0.2.1-2.eos4.noarch
ruby(abi) = %{rubyabi} is needed by rubygem-rbeapi-0.1.0-2.eos4.noarch

sw1(config)#extension rbeapi-0.1.0-eos4.swix force
sw1(config)#sho extensions
Name                                       Version/Release           Status extension
------------------------------------------ ------------------------- ------ ----
EosCliForSplunk-1.1.2.rpm                  1.1.2/1.fc14              A, I      1
Telemetry-1.1.2.rpm                        1.1.2/1                   A, I      1
puppet-enterprise-3.8.0-eos-4-i386.swix    3.8.0.3/1.pe.eos4         A, NI    21
rbeapi-0.1.0-eos4.swix                     3.0.0/2.eos4              A, F      7
splunkforwarder-6.2.2-255606.i386.rpm      6.2.2/255606              A, I      1

A: available | NA: not available | I: installed | NI: not installed | F: forced
sw1(config)#extension puppet-enterprise-3.8.0-eos-4-i386.swix
sw1(config)#

sw1(config)#puppet resource --types
augeas
computer
cron
exec
file
filebucket
group
host
interface
k5login
macauthorization
mailalias
maillist
..
..
sw1(config)#puppet resource --types | grep eos
'sudo puppet resource --types | grep eos' returned error code:1

**Comment by jerearista** [comment]
Steve,
  From the output, it looks like 'swix create' was successful but you hit a dependency issue when trying to install the extensions.  The rubygems in the swix are expecting ruby to be installed, first.   Since you have the puppet-enterprise extension, that includes ruby so generally, install that first, then use the "pe-*" rbeapi extension as its configured to use the ruby supplied with puppet enterprise and everything should go smoothly.

Down the output, it looks like you have puppet installed, successfully, too.  Great.    Don't expect to see the eos_* Types until they have been synced down from the master with pluginsync.  This is automatic once you have the master setup with those and then run 'puppet agent' on the node, after the certificate has been signed, etc. (If you're doing puppet headless, there's a different process.)

To specifically verify rbeapi (and ruby, etc) try using rbeapi from the ruby shell (the connect, below will use unix-sockets by default):

    Arista# bash /opt/puppet/bin/irb 
    irb(main):001:0> require 'rbeapi/client'
    irb(main):002:0> node = Rbeapi::Client.connect_to('localhost')
    irb(main):003:0> node.enable('show version')

If you have any issue with that, you may need to create `flash:eapi.conf` with the following content:

    [connection:localhost]
    host: localhost
    transport: socket

**Comment by lunarman** [comment]
Got it. i decided to 'gem install rbeapi' in my eos node.
i will ask how to get the eos_* types usable in the next thread.
Thanks again.

**Comment by jerearista** [comment]
Great.  Here's a jumpstart on the eos_ types... http://puppet-eos.readthedocs.org/en/master/quickstart.html

**Comment by pa-grape** [comment]
Hola, 
I have problem, too. 
Mine is Centos6.6. I can not even create rbeapi RPMs. How to do it?
See below:

[root@ppm rbeapi]# rake all_rpms
rbeapi 0.1.0 built to pkg/rbeapi-0.1.0.gem.
WARNING:  open-ended dependency on net_http_unix (>= 0) is not recommended
  if net_http_unix is semantically versioned, use:
    add_runtime_dependency 'net_http_unix', '~> 0'
WARNING:  open-ended dependency on inifile (>= 0) is not recommended
  if inifile is semantically versioned, use:
    add_runtime_dependency 'inifile', '~> 0'
WARNING:  open-ended dependency on yard (>= 0, development) is not recommended
  if yard is semantically versioned, use:
    add_development_dependency 'yard', '~> 0'
WARNING:  open-ended dependency on redcarpet (>= 0, development) is not recommended
  if redcarpet is semantically versioned, use:
    add_development_dependency 'redcarpet', '~> 0'
WARNING:  pessimistic dependency on rake (~> 10.1.0, development) may be overly strict
  if rake is semantically versioned, use:
    add_development_dependency 'rake', '~> 10.1', '>= 10.1.0'
WARNING:  pessimistic dependency on rspec (~> 3.0.0, development) may be overly strict
  if rspec is semantically versioned, use:
    add_development_dependency 'rspec', '~> 3.0', '>= 3.0.0'
WARNING:  pessimistic dependency on rspec-mocks (~> 3.0.0, development) may be overly strict
  if rspec-mocks is semantically versioned, use:
    add_development_dependency 'rspec-mocks', '~> 3.0', '>= 3.0.0'
WARNING:  open-ended dependency on simplecov (>= 0, development) is not recommended
  if simplecov is semantically versioned, use:
    add_development_dependency 'simplecov', '~> 0'
WARNING:  See http://guides.rubygems.org/specification-reference/ for help
  Successfully built RubyGem
  Name: rbeapi
  Version: 0.1.0
  File: rbeapi-0.1.0.gem
Executing(%prep): /bin/sh -e /var/tmp/rpm-tmp.hO5Utz
+ umask 022
+ cd /home/root/Downloads/rbeapi/rpmbuild
+ LANG=C
+ export LANG
+ unset DISPLAY
+ cd /home/root/Downloads/rbeapi/rpmbuild
+ cd .
+ /bin/chmod -Rf a+rX,u+w,g-w,o-w .
+ exit 0
Executing(%install): /bin/sh -e /var/tmp/rpm-tmp.Htvtar
+ umask 022
+ cd /home/root/Downloads/rbeapi/rpmbuild
+ '[' /home/root/Downloads/rbeapi/rpmbuild/BUILDROOT/rubygem-rbeapi-0.1.0-1.eos4.x86_64 '!=' / ']'
+ rm -rf /home/root/Downloads/rbeapi/rpmbuild/BUILDROOT/rubygem-rbeapi-0.1.0-1.eos4.x86_64
++ dirname /home/root/Downloads/rbeapi/rpmbuild/BUILDROOT/rubygem-rbeapi-0.1.0-1.eos4.x86_64
+ mkdir -p /home/root/Downloads/rbeapi/rpmbuild/BUILDROOT
+ mkdir /home/root/Downloads/rbeapi/rpmbuild/BUILDROOT/rubygem-rbeapi-0.1.0-1.eos4.x86_64
+ cd .
+ LANG=C
+ export LANG
+ unset DISPLAY
+ install /home/root/Downloads/rbeapi/rbeapi-0.1.0.gem /home/root/Downloads/rbeapi/rpmbuild/BUILDROOT/rubygem-rbeapi-0.1.0-1.eos4.x86_64/
+ /usr/lib/rpm/check-buildroot
+ /usr/lib/rpm/redhat/brp-compress
+ /usr/lib/rpm/redhat/brp-strip /usr/bin/strip
+ /usr/lib/rpm/redhat/brp-strip-static-archive /usr/bin/strip
+ /usr/lib/rpm/redhat/brp-strip-comment-note /usr/bin/strip /usr/bin/objdump
+ /usr/lib/rpm/brp-python-bytecompile
+ /usr/lib/rpm/redhat/brp-python-hardlink
+ /usr/lib/rpm/redhat/brp-java-repack-jars
Processing files: rubygem-rbeapi-0.1.0-1.eos4.noarch
Provides: ruby(rbeapi) = 0.1.0-1.eos4
Requires(interp): /bin/sh /bin/sh
Requires(rpmlib): rpmlib(CompressedFileNames) <= 3.0.4-1 rpmlib(FileDigests) <= 4.6.0-1 rpmlib(PayloadFilesHavePrefix) <= 4.0-1 rpmlib(VersionedDependencies) <= 3.0.3-1
Requires(post): /bin/sh
Requires(preun): /bin/sh
Checking for unpackaged file(s): /usr/lib/rpm/check-files /home/root/Downloads/rbeapi/rpmbuild/BUILDROOT/rubygem-rbeapi-0.1.0-1.eos4.x86_64
Wrote: /home/root/Downloads/rbeapi/rpms/noarch/rubygem-rbeapi-0.1.0-1.eos4.noarch.rpm
Executing(%clean): /bin/sh -e /var/tmp/rpm-tmp.jASqyb
+ umask 022
+ cd /home/root/Downloads/rbeapi/rpmbuild
+ cd .
+ /bin/rm -rf /home/root/Downloads/rbeapi/rpmbuild/BUILDROOT/rubygem-rbeapi-0.1.0-1.eos4.x86_64
+ exit 0
Executing(%prep): /bin/sh -e /var/tmp/rpm-tmp.N8oSh0
+ umask 022
+ cd /home/root/Downloads/rbeapi/rpmbuild
+ LANG=C
+ export LANG
+ unset DISPLAY
+ cd /home/root/Downloads/rbeapi/rpmbuild
+ cd .
+ /bin/chmod -Rf a+rX,u+w,g-w,o-w .
+ exit 0
Executing(%install): /bin/sh -e /var/tmp/rpm-tmp.2sFE1S
+ umask 022
+ cd /home/root/Downloads/rbeapi/rpmbuild
+ '[' /home/root/Downloads/rbeapi/rpmbuild/BUILDROOT/pe-rubygem-rbeapi-0.1.0-1.eos4.x86_64 '!=' / ']'
+ rm -rf /home/root/Downloads/rbeapi/rpmbuild/BUILDROOT/pe-rubygem-rbeapi-0.1.0-1.eos4.x86_64
++ dirname /home/root/Downloads/rbeapi/rpmbuild/BUILDROOT/pe-rubygem-rbeapi-0.1.0-1.eos4.x86_64
+ mkdir -p /home/root/Downloads/rbeapi/rpmbuild/BUILDROOT
+ mkdir /home/root/Downloads/rbeapi/rpmbuild/BUILDROOT/pe-rubygem-rbeapi-0.1.0-1.eos4.x86_64
+ cd .
+ LANG=C
+ export LANG
+ unset DISPLAY
+ install /home/root/Downloads/rbeapi/rbeapi-0.1.0.gem /home/root/Downloads/rbeapi/rpmbuild/BUILDROOT/pe-rubygem-rbeapi-0.1.0-1.eos4.x86_64/
+ /usr/lib/rpm/check-buildroot
+ /usr/lib/rpm/redhat/brp-compress
+ /usr/lib/rpm/redhat/brp-strip /usr/bin/strip
+ /usr/lib/rpm/redhat/brp-strip-static-archive /usr/bin/strip
+ /usr/lib/rpm/redhat/brp-strip-comment-note /usr/bin/strip /usr/bin/objdump
+ /usr/lib/rpm/brp-python-bytecompile
+ /usr/lib/rpm/redhat/brp-python-hardlink
+ /usr/lib/rpm/redhat/brp-java-repack-jars
Processing files: pe-rubygem-rbeapi-0.1.0-1.eos4.noarch
Provides: pe-rubygem(rbeapi) = 0.1.0 pe-rubygem-rbeapi = 0.1.0
Requires(interp): /bin/sh /bin/sh
Requires(rpmlib): rpmlib(CompressedFileNames) <= 3.0.4-1 rpmlib(FileDigests) <= 4.6.0-1 rpmlib(PayloadFilesHavePrefix) <= 4.0-1 rpmlib(VersionedDependencies) <= 3.0.3-1
Requires(post): /bin/sh
Requires(preun): /bin/sh
Checking for unpackaged file(s): /usr/lib/rpm/check-files /home/root/Downloads/rbeapi/rpmbuild/BUILDROOT/pe-rubygem-rbeapi-0.1.0-1.eos4.x86_64
Wrote: /home/root/Downloads/rbeapi/rpms/noarch/pe-rubygem-rbeapi-0.1.0-1.eos4.noarch.rpm
Executing(%clean): /bin/sh -e /var/tmp/rpm-tmp.0r2byF
+ umask 022
+ cd /home/root/Downloads/rbeapi/rpmbuild
+ cd .
+ /bin/rm -rf /home/root/Downloads/rbeapi/rpmbuild/BUILDROOT/pe-rubygem-rbeapi-0.1.0-1.eos4.x86_64
+ exit 0
RPMs are available in rpms/noarch/
Usage: awk [POSIX or GNU style options] -f progfile [--] file ...
Usage: awk [POSIX or GNU style options] [--] 'program' file ...
POSIX options:		GNU long options:
	-f progfile		--file=progfile
	-F fs			--field-separator=fs
	-v var=val		--assign=var=val
	-m[fr] val
	-O			--optimize
	-W compat		--compat
	-W copyleft		--copyleft
	-W copyright		--copyright
	-W dump-variables[=file]	--dump-variables[=file]
	-W exec=file		--exec=file
	-W gen-po		--gen-po
	-W help			--help
	-W lint[=fatal]		--lint[=fatal]
	-W lint-old		--lint-old
	-W non-decimal-data	--non-decimal-data
	-W profile[=file]	--profile[=file]
	-W posix		--posix
	-W re-interval		--re-interval
	-W source=program-text	--source=program-text
	-W traditional		--traditional
	-W usage		--usage
	-W use-lc-numeric	--use-lc-numeric
	-W version		--version

To report bugs, see node `Bugs' in `gawk.info', which is
section `Reporting Problems and Bugs' in the printed version.

gawk is a pattern scanning and processing language.
By default it reads standard input and writes standard output.

Examples:
	gawk '{ sum += $1 }; END { print sum }' file
	gawk -F: '{ print $1 }' /etc/passwd
ERROR:  While executing gem ... (Gem::Requirement::BadRequirementError)
    Illformed requirement ["="]
Building rpm for inifile ()
error: line 5: Empty tag: Version:
error: line 5: Empty tag: Version:
RPMs are available in rpms/noarch/
Usage: awk [POSIX or GNU style options] -f progfile [--] file ...
Usage: awk [POSIX or GNU style options] [--] 'program' file ...
POSIX options:		GNU long options:
	-f progfile		--file=progfile
	-F fs			--field-separator=fs
	-v var=val		--assign=var=val
	-m[fr] val
	-O			--optimize
	-W compat		--compat
	-W copyleft		--copyleft
	-W copyright		--copyright
	-W dump-variables[=file]	--dump-variables[=file]
	-W exec=file		--exec=file
	-W gen-po		--gen-po
	-W help			--help
	-W lint[=fatal]		--lint[=fatal]
	-W lint-old		--lint-old
	-W non-decimal-data	--non-decimal-data
	-W profile[=file]	--profile[=file]
	-W posix		--posix
	-W re-interval		--re-interval
	-W source=program-text	--source=program-text
	-W traditional		--traditional
	-W usage		--usage
	-W use-lc-numeric	--use-lc-numeric
	-W version		--version

To report bugs, see node `Bugs' in `gawk.info', which is
section `Reporting Problems and Bugs' in the printed version.

gawk is a pattern scanning and processing language.
By default it reads standard input and writes standard output.

Examples:
	gawk '{ sum += $1 }; END { print sum }' file
	gawk -F: '{ print $1 }' /etc/passwd
ERROR:  While executing gem ... (Gem::Requirement::BadRequirementError)
    Illformed requirement ["="]
Building rpm for net_http_unix ()
error: line 5: Empty tag: Version:
RPMs are available in rpms/noarch/
RPMs are available in rpms/noarch/
Copy the RPMs to an EOS device then run the 'swix create' command.
  Example: cd /mnt/flash; swix create rbeapi-0.1.0-1.swix \
           rubygem-rbeapi-0.1.0-1.eos4.noarch.rpm \
           rubygem-inifile-3.0.0-1.eos4.noarch.rpm \
           rubygem-net_http_unix-0.2.1-1.eos4.noarch.rpm
  For PE:: cd/mnt/flash; swix create pe-rbeapi-0.1.0-1.swix \
           pe-rubygem-rbeapi-0.1.0-1.eos4.noarch.rpm \
           pe-rubygem-inifile-3.0.0-1.eos4.noarch.rpm
[root@ppm rbeapi]#


======
Gracias.
- jO

**Comment by pa-grape** [comment]
Hola,
I have ruby 1.9.3p551 (2014-11-13 revision 48407) [x86_64-linux] to make rbeapi RPMs.  
How do you install extension in my DCS, it complaining:

iDCS3(config)#extension rbeapi.swix
% Error installing rbeapi.swix: RPM install error: Transaction check failed: ruby(abi) = %{rubyabi} is needed by rubygem-inifile-3.0.0-1.eos4.noarch
ruby(abi) = %{rubyabi} is needed by rubygem-rbeapi-0.1.0-1.eos4.noarch
ruby(abi) = %{rubyabi} is needed by rubygem-net_http_unix-0.2.1-1.eos4.noarch
iDCS3(config)#sho extensions
Name                                       Version/Release           Status extension
------------------------------------------ ------------------------- ------ ----
puppet-enterprise-3.8.0-eos-4-i386.swix    3.8.0.3/1.pe.eos4         A, I     21
rbeapi.swix                                3.0.0/1.eos4              A, NI     5

A: available | NA: not available | I: installed | NI: not installed | F: forced

----
Gracias,
-jO

**Comment by jerearista** [comment]
When using the puppet-enterprise package, which includes ruby, use the pe-rbeapi swix that is configured for the alternate ruby path.

**Comment by pa-grape** [comment]
Thank you.
That solved my problem.
Now, can you help again? I can not do this in the switch, but I can do it in my server.
Is it 1.9.1 (Puppet Enterprise 3.8.0 extension in my switch) different than 1.9.3 (Centos 6.6, RVM), yes?
Can you fix?

switch:
bash-4.1# cat eapi.conf
[connection:iDCS3]
host: 192.168.56.12
username: admin
password: admin
transport: socket
bash-4.1# irb
irb(main):001:0>
irb(main):002:0* require 'rbeapi/client'
=> true
irb(main):003:0> Rbeapi::Client.load_config('./eapi.conf')
=> {:transport=>"socket"}
irb(main):004:0> Rbeapi::Client.load_config('/mnt/flash/eapi.conf')
=> {:transport=>"socket"}
irb(main):005:0> node = Rbeapi::Client.connect_to('iDCS3')
=> #<Rbeapi::Client::Node:0x9a1008c @connection=#<Rbeapi::Eapilib::HttpEapiConnection:0x9a10230 @transport=#<Net::HTTP 192.168.56.12:80 open=false>, @error=nil, @username="admin", @password="admin">, @autorefresh=true>
irb(main):006:0> node.enable('show hostname')
ArgumentError: wrong number of arguments (2 for 1)
   from /opt/puppet/lib/ruby/gems/1.9.1/gems/rbeapi-0.1.0/lib/rbeapi/eapilib.rb:232:in `send'
   from /opt/puppet/lib/ruby/gems/1.9.1/gems/rbeapi-0.1.0/lib/rbeapi/eapilib.rb:280:in `execute'
   from /opt/puppet/lib/ruby/gems/1.9.1/gems/rbeapi-0.1.0/lib/rbeapi/client.rb:399:in `run_commands'
   from /opt/puppet/lib/ruby/gems/1.9.1/gems/rbeapi-0.1.0/lib/rbeapi/client.rb:351:in `block in enable'
   from /opt/puppet/lib/ruby/gems/1.9.1/gems/rbeapi-0.1.0/lib/rbeapi/client.rb:349:in `each'
   from /opt/puppet/lib/ruby/gems/1.9.1/gems/rbeapi-0.1.0/lib/rbeapi/client.rb:349:in `enable'
   from (irb):6
   from /opt/puppet/bin/irb:12:in `<main>'
irb(main):007:0>


server:

1.9.3-p551 :004 > Rbeapi::Client.load_config('./eapi.conf')
 => {:transport=>"socket"}  ** This is a bug, yes? I use http.
1.9.3-p551 :005 > node = Rbeapi::Client.connect_to('iDCS3')
 => #<Rbeapi::Client::Node:0x00000002e4dd18 @connection=#<Rbeapi::Eapilib::HttpEapiConnection:0x00000002e4dfc0 @transport=#<Net::HTTP iDCS3:80 open=false>, @error=nil, @username="admin", @password="admin">, @autorefresh=true>
1.9.3-p551 :006 > node.enable('show hostname')
 => [{:command=>"show hostname", :result=>{"fqdn"=>"iDCS3.domain.com", "hostname"=>"iDCS3"}, :encoding=>"json"}]


Gracias again.
-jO

**Comment by jerearista** [comment]
In the eapi.conf, above, you have the transport listed as "socket" which will work locally on the switch and does not require a host, username or password entry.  If you wish to use the same name, iCS3, from the switch, all you need in `/mnt/flash/eapi.conf` is:

    [Connection:iDCS3]
    transport: socket

Then you can make your connection:

    -bash-4.1# /opt/puppet/bin/irb 
    irb(main):001:0> require 'rbeapi/client'
    => true
    irb(main):003:0> node = Rbeapi::Client.connect_to('iDCS3')
    => #<Rbeapi::Client::Node:0x9875614 @connection=#      <Rbeapi::Eapilib::SocketEapiConnection:0x98757e0 @transport=#<NetX::HTTPUnix localhost:80 open=false>, @error=nil>, @autorefresh=true>
    irb(main):004:0> node.enable('show version')
    => [{:command=>"show version", :result=>{"modelName"=>"vEOS", "internalVersion"=>"4.14.6M-2307053.4146M", "systemMacAddress"=>"08:00:27:e2:c5:d5", "serialNumber"=>"", "memTotal"=>2028800, "bootupTimestamp"=>1432842053.36, "memFree"=>110392, "version"=>"4.14.6M", "architecture"=>"i386", "internalBuildId"=>"9530b847-15dc-4ae1-9156-9cde18ff7982", "hardwareRevision"=>""}, :encoding=>"json"}]

**Comment by jerearista** [comment]
PR was merged in to develop.
