### ISSUE TITLE
client.enable ('show interface status > flash:status') does not write to flash

### ISSUE THREAD

**Issue by PeiwenChen** [arista-eosplus/rbeapi#133]
Hi @devrobo 

I have an Arista client and all the other commands running successfully, but this one failed:
```
client.enable('show interfaces status > flash:pre-upgrade-int-status-test')
```
It did generate a file in flash, but its empty:
```
 -rwx           0           Jun 21 20:07  pre-upgrade-int-status-test
```

Is this a bug?

Thanks,

**Comment by jerearista** [comment]
This may be slightly confusing, but by default, we attempt to retrieve the results from all commands as structured JSON data.  You can accomplish the goal, above, by specifying the encoding as text:
```
node.enable('show interfaces status > flash:test', encoding: "text")
=> [{:command=>"show interfaces status > flash:test", :result=>{"output"=>""}, :encoding=>"text"}]
```

Does that address your needs?
