### ISSUE TITLE
eapi.conf: Password not read correctly with #

### ISSUE THREAD

**Issue by pdenitto** [arista-eosplus/rbeapi#157]
Given the following eapi.conf:

```
[connection:*]
username: eapiuser
password: GotA#InMyPassword
```

The eapi client will be unable to connect as the password is not passed correctly.

**Comment by jerearista** [comment]
I apologize for the extreme delay in responding.   This is actually an issue with the comment handling within the [inifile Rubygem](https://github.com/twp/inifile) but can be handled by surrounding the value with double-quotes

```
[connection:*]
username: eapiuser
password: "GotA#InMyPassword"
```
