### ISSUE TITLE
Error installing rbeapi-chef-1.2-1.swix: RPM install error

### ISSUE THREAD

**Issue by rushins** [arista-eosplus/rbeapi#177]
hi 

I am getting the following error on Arista DCS-7150S-64-CL-R switch while installing extension rbeapi-chef-1.2-1.swix

% Error installing rbeapi-chef-1.2-1.swix: RPM install error: Transaction check failed: chef is needed by rubygem-rbeapi-chef-1.2-1.eos4.noarch
chef is needed by rubygem-inifile-chef-3.0.0-5.eos4.noarch
chef is needed by rubygem-netaddr-chef-1.5.1-4.eos4.noarch
chef is needed by rubygem-net_http_unix-chef-0.2.2-5.eos4.noarch

Here is the Arista switch release.

Arista DCS-7150S-64-CL-R
Hardware version:    01.02
Serial number:       JPE13370490
System MAC address:  001c.7341.4cb3

Software image version: 4.13.14M
Architecture:           i386

**Comment by devrobo** [comment]
Hi,
Did you install the Chef client first before installing rbeapi? The instructions for using Chef on EOS can be found at: https://github.com/aristanetworks/chef-eos

**Comment by rushins** [comment]
thank you. @devrobo : i missed that first ..now i have installed CHEF and rbeapi-chef-1.2-1.swix . no errors now. i will fire up my cookbooks now and see how that goes.

thank you again for pointing me to the right documentation

**Comment by devrobo** [comment]
Glad to hear that it installed fine.
