### ISSUE TITLE
Add [connection:*] to eapi.conf syntax

### ISSUE THREAD

**Issue by privateip** [arista-eosplus/rbeapi#18]
this will provide a default connection profile for connection names that do not have a more specific entry in eapi.conf.

```
[connection:eos01]
username: eapi
password: password
transport: http

[connection:*]
username: eapi
password: password
transport: http
```

In the above example a connection to any hostname other than eos01 will result in a connection using the section entry defined as ```[connection:*]```

This is related to PR #15

**Comment by devrobo** [comment]
Fixed with change 235ace5e11993905aa3c61bc90214d6222be181a
