### ISSUE TITLE
Enable password setting in the .eapi.conf file not honored

### ISSUE THREAD

**Issue by charlescng** [arista-eosplus/rbeapi#72]
It doesn't seem to be used.

`enablepwd` is referenced in the `eapi.conf` section of the README.

There is a reference to `enable_pwd` in https://github.com/arista-eosplus/rbeapi/blob/develop/lib/rbeapi/client.rb#L125 though I can't see where it's being used.

The only way I could get enable mode to work is calling `node.enable_authentication` with the password explicitly.

I'd submit a patch except I can't seem to get the tests to run cleanly (on master) against vEOS. Who do I get help with that?

**Comment by jerearista** [comment]
Release Note:
``enablepwd`` is now properly used, if defined, in the ``eapi.conf``
