### ISSUE TITLE
failure when eapi.conf is not formatted correctly

### ISSUE THREAD

**Issue by devrobo** [arista-eosplus/rbeapi#82]
pyeapi should not crash when an eapi.conf file is not properly formatted. Perhaps we could wrap SafeConfigParser in a try/except block and just throw a warning that the file did not parse.

Background, in some cases, where the application does not make use of the eapi.conf, but uses the connect() method, instead, the existence of a file named eapi.conf could cause the application to fail.

**Comment by jerearista** [comment]
Release Note:
In the event of an unparsable ``eapi.conf`` file, which could occur due to other tools which used a YAML syntax instead of INI, rbeapi will log a warning via syslog, but continue to attempt a default connection to localhost.
