### ISSUE TITLE
Wildcard connection config gets clobbered

### ISSUE THREAD

**Issue by charlescng** [arista-eosplus/rbeapi#86]
Given the following configuration:
```
[connection:*]
username: foo
password: bar
```
Given the following code:
```ruby
client = Rbeapi::Client.connect_to('host1')
client = Rbeapi::Client.connect_to('host2')
```
The `config['host']` of value `*` is clobbered to `host1`: https://github.com/arista-eosplus/rbeapi/blob/develop/lib/rbeapi/client.rb#L104

The second call to `connect_to('host2')` has a `config['host']` value of `host1`

It should probably `.dup` the configuration before modifying `config['host']`.

**Comment by devrobo** [comment]
Thank you for reporting this bug, we will get it fixed.
